### ISSUE TITLE
To add Librosa's icon to the tab instead of a blank icon.

### ISSUE THREAD

**Issue by AKBuggy** [librosa/librosa.github.io#2]
![image](https://github.com/librosa/librosa.github.io/assets/95762611/59a20d22-255a-4fcb-8c4c-19a0dede5c28)

To add Librosa's icon to the tab instead of a blank icon.

**Comment by bmcfee** [comment]
As noted in the pr, this repo is not the place to address this issue. Documentation is automatically built and deployed from the main librosa repo, so any changes to the documentation site need to be made over there.
